name = "ahnaf-portfolio"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 database configuration
[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "aeb9dbbf-b48f-4563-aafd-682e1654fa79"

[env.production]
name = "ahnaf-portfolio"

[site]
bucket = "./dist"
